// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp_fZBWxHwZXdJnzXjUiTCIb7Fei6rU3o',
    appId: '1:1042125956309:web:7f31f4fe409e44887e2e5c',
    messagingSenderId: '1042125956309',
    projectId: 'recipe-app-19207',
    authDomain: 'recipe-app-19207.firebaseapp.com',
    storageBucket: 'recipe-app-19207.firebasestorage.app',
    measurementId: 'G-01P1MKGHVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIKqC_OsFBcIpLuK-78tyUubBCAjYcl4Q',
    appId: '1:1042125956309:android:332836bf85fbb6747e2e5c',
    messagingSenderId: '1042125956309',
    projectId: 'recipe-app-19207',
    storageBucket: 'recipe-app-19207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJqpuXvGsc442_Ki-pXIBN9Ottqev5Jkw',
    appId: '1:1042125956309:ios:6c4821ef524f028d7e2e5c',
    messagingSenderId: '1042125956309',
    projectId: 'recipe-app-19207',
    storageBucket: 'recipe-app-19207.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJqpuXvGsc442_Ki-pXIBN9Ottqev5Jkw',
    appId: '1:1042125956309:ios:6c4821ef524f028d7e2e5c',
    messagingSenderId: '1042125956309',
    projectId: 'recipe-app-19207',
    storageBucket: 'recipe-app-19207.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp_fZBWxHwZXdJnzXjUiTCIb7Fei6rU3o',
    appId: '1:1042125956309:web:79eba986b78ddc3a7e2e5c',
    messagingSenderId: '1042125956309',
    projectId: 'recipe-app-19207',
    authDomain: 'recipe-app-19207.firebaseapp.com',
    storageBucket: 'recipe-app-19207.firebasestorage.app',
    measurementId: 'G-PC90ZDKES7',
  );

}